# Generated by Django 4.2.6 on 2023-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arithmetic', models.CharField(max_length=1000, verbose_name='算术表达式')),
                ('out', models.CharField(max_length=1000, verbose_name='计算结果')),
            ],
            options={
                'verbose_name': 'Calculations',
                'db_table': 'Calculations',
            },
        ),
    ]
